### ISSUE TITLE
Folder list not display in folder field!

### ISSUE THREAD

**Issue by ribsousa** [ChristianGiupponi/PyroCMS-Galleries#2]
The folder list is not displayed in the Folder field. using pyro 2.2.3 
With that you can not create a gallery 

After the installation, checking the module file five folders were created: 

Galleries Folder 
Galleries Folder-1 
Galleries Folder-2 
Galleries Folder-3 
Galleries Folder-4 

Is this correct?

**Comment by ChristianGiupponi** [comment]
No, you should have just one folder.
Can you please uninstall the module, remove all the folders listed above and then reinstall the module?

You should have just the first named **Galleries Folder**

**Comment by ribsousa** [comment]
Sorry for the delay, I removed and reinstalled the module now work correctly. 

Thank you! 

There is a forecast for pyro upgrade to 2.3?

**Comment by ChristianGiupponi** [comment]
Great!
Yes, I will update the module for the 2.3 but there is no documentation right now about how to develop module/fields_types

**Comment by keevitaja** [comment]
I have the same problem... Deleted all folders and reinstalled the module, but still no folders found. I have only one Galleries Folder!

**Comment by ChristianGiupponi** [comment]
@keevitaja did you create andy folder within the Galleries Folder?
you should have something like:

```
Galleries Folder
    \_ Gallery 1
    \_ Gallery 2
```

The field type will list these folder

**Comment by keevitaja** [comment]
OK, my fault. RTFM
