### ISSUE TITLE
creating category and galleries

### ISSUE THREAD

**Issue by Gutty0** [ChristianGiupponi/PyroCMS-Galleries#3]
Hi Christian, thanks a lot for this module.

I'm at a stopping point where I have created some folders in the gallery files section. 
but i go to add a category or gallery and its saying the folder is not there 
example:
The requested URL /admin/galleries/create was not found on this server.
The requested URL /admin/galleries/categories/create was not found on this server.

I get this buy clicking the link "There are no Category. Add one."
I have looked through my entire folder and don't see it.

Any ideas? 
Thanks.
Dave.

**Comment by ChristianGiupponi** [comment]
Hi Dave,
did you installed PyroCMS with the `mod_rewrite` option?
if you do not installed it please try to add `index.php` just before the admin segment, you should have something like:

```
www.site.com/index.php/admin/galleries/create
```

and

```
www.site.com/index.php/admin/galleries/categories/create
```

**Comment by Gutty0** [comment]
ok thanks. I did not use mod_rewrite.

i feel like an idiot now, just before i seen your reply, i seen the link on the top right corner. 
I have added category and gallery now.

many thanks for your prompt reply.

**Comment by ChristianGiupponi** [comment]
Glad you solved!
If you have any pther issue let me know
