### ISSUE TITLE
Error when edit and click save gallery

### ISSUE THREAD

**Issue by ribsousa** [ChristianGiupponi/PyroCMS-Galleries#4]
PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$keywords

Filename: keywords/field.keywords.php

Line Number: 61

**Comment by ChristianGiupponi** [comment]
This is a problem with the field type, not the module.
Which version of PyroCMS are you using?

**Comment by ribsousa** [comment]
Pyro 2.2.3

**Comment by ChristianGiupponi** [comment]
Sorry for the delay, can you please make sure that your file match this one?

https://github.com/pyrocms/pyrocms/blob/2.2/master/system/cms/modules/streams_core/field_types/keywords/field.keywords.php

**Comment by ribsousa** [comment]
Yes, it´s match

**Comment by ChristianGiupponi** [comment]
Do you have an online demo to check it?
