### ISSUE TITLE
Add Gallery to Pages

### ISSUE THREAD

**Issue by myrafletcher** [ChristianGiupponi/PyroCMS-Galleries#5]
I have created some galleries now how do I add them to my pages?

**Comment by ChristianGiupponi** [comment]
just visit: yoursite.com/galleries

**Comment by myrafletcher** [comment]
Okay there isn't a way to put the gallery into a page? Is there a way to add a custom form to a page?

**Comment by ChristianGiupponi** [comment]
I have just add a plugin so now you can get all the galleries in a page, just use:

```
{{ gelleries:get_galleries }} 
    {{ galleries_name }} 
{{ /gelleries:get_galleries }}
```

If you need a form in the page you have to code it by yourself, the module don't do that

**Comment by myrafletcher** [comment]
Ok that's fine I see now how I can add code, thank you very much for the kind assistance.
