### ISSUE TITLE
Folder list not showing 

### ISSUE THREAD

**Issue by trsmadhu** [ChristianGiupponi/PyroCMS-Galleries#6]
When i am trying to create a new gallery, it does not showing the folder list in the files module. I have installed the module as per the instruction in the doc. Advance thanks for the help.

**Comment by ChristianGiupponi** [comment]
Hi @trsmadhu,  
did you create any folder inside the main folder created by the module? The select wil be populated only with the folders created inside the default one

**Comment by trsmadhu** [comment]
But that gallery is not working form me. I have created folders as you described in the document. i ask this for one of my project . Now  i am using  file manager for the gallery. Thank you for your support.
