### ISSUE TITLE
how can i get the category list?

### ISSUE THREAD

**Issue by thejerry** [ChristianGiupponi/PyroCMS-Galleries#8]
Hi, I'm trying to get the category list, is possible to do something like this:

< ul >
{{ galleries }}
     < li >< a href="{{url}}">{{ galleries_category }}< /a>< /li >
{{ /galleries }}
< /ul >

in free or pro version?
Bless!!

**Comment by ChristianGiupponi** [comment]
You can do it in both version, I have just add a new method in plugin file, please have a look:https://github.com/ChristianGiupponi/PyroCMS-Galleries/commit/f336b4d6a434c80511d8f1e3572c4416b75233e3

**Comment by thejerry** [comment]
Very nice!! tks Christian!!

**Comment by ChristianGiupponi** [comment]
you're welcome!
